import Banner from "@/components/banner/Banner";
import Contact from "@/components/contact/Contact";
import Breadcrumbs from "@/components/breadcrumbs/Breadcrumbs";
// images
import banner from "@/assets/banner/contactbanner.png";
import bannermob from "@/assets/banner/contactbannermob.png";
import Map from "@/components/map/Map";
export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};
const page = () => {
  const breadcrumbs = [{ label: "Home", href: "/" }, { label: "Contact Us" }];
  return (
    <>
      <Banner
        banner={banner}
        mobilebanner={bannermob}
        text="Get in Touch with Our Cricket Experts"
      />
      {/* contact */}
      <div className="container">
        <Breadcrumbs paths={breadcrumbs} />
      </div>
      <Contact />
      {/* map */}
      <Map />
    </>
  );
};

export default page;
