import Image from "next/image";
import Banner from "@/components/banner/Banner";
// IMAGES
import banner from "@/assets/banner/coachesbanner.png";
import bannermob from "@/assets/banner/coachesbannermob.png";
import coaches from "@/assets/coache.png";
import srilanka from "@/assets/srilanka.png";
import players from "@/assets/players.png";
import messageblue from "@/assets/messageblue.png";
import message from "@/assets/messageicon.png";
import CoachTestimonial from "@/UI/slider/CoachTestimonial";
import Coach from "@/components/coach/Coach";
export const metadata = {
  title: "Coaches",
  description: "Generated by create next app",
};
const pages = () => {
  return (
    <>
      {/* Banner */}
      <Banner
        banner={banner}
        mobilebanner={bannermob}
        text="Transformative Coaching for Your Best Self"
      />
      {/* coaches */}
      <section className="section_top">
        <div className="container">
          <div className="grid-2-to-2 gap5">
            <div>
              <h2 className="title text-blue rocket">Head coach</h2>
              <h3 className="middletext text-red lg-text-center">
                Hasantha Mendis
              </h3>
              <div className="mobileview">
                <Image
                  src={coaches}
                  alt="cricket player"
                  className="img-fluid block margin-auto"
                />
              </div>
              <p className="paragraph text-gray full-text-justify mt-2">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis
                cumque itaque, dolorem sapiente quisquam rem porro impedit.
                Numquam neque nobis at deserunt culpa officia quos, temporibus,
                est aperiam commodi atque doloremque praesentium hic. Atque
                pariatur dicta ad quasi facere consectetur minus eaque quaerat
                ducimus, fuga excepturi doloribus eveniet recusandae culpa
                exercitationem, dolor soluta qui quas beatae amet! Fugiat a quae
                ipsam aut delectus velit minima vitae eius consectetur, optio
                distinctio esse dolore obcaecati. Labore, id? Quam vitae
                voluptatem autem iure, officia, est sit atque blanditiis modi
                fugiat vel nulla beatae, temporibus quas nemo nostrum neque enim
                quo minima repellat! Iusto?
              </p>
              {/* <div className="mt-2 mobile-flex-center">
                <Button>VIEW MORE</Button>
              </div> */}
            </div>
            <div className="desktopview">
              <Image src={coaches} alt="cricket player" className="img-fluid" />
            </div>
          </div>
        </div>
      </section>
      {/* srilanka */}
      <section className="section_top ">
        <div className="container">
          <div className="sectionpadingfull bg3">
            <div className="grid_1_to_2 gap5">
              <div className="desktopview">
                <Image
                  src={srilanka}
                  alt="cricket player"
                  className="img-fluid block margin-auto"
                />
              </div>
              <div>
                <h2 className="title text-blue rocket">
                  Playing Career Highlights
                </h2>
                <div className="mobileview mt-2">
                  <Image
                    src={srilanka}
                    alt="cricket player"
                    className="img-fluid block margin-auto"
                  />
                </div>
                <p className="paragraph text-gray justify-center mt-2">
                  Lorem ipsum dolor sit amet consectetur. Et ante imperdiet
                  porttitor vulputate id. Ultrices id lectus lectus consequat
                  porttitor lobortis. Morbi sit nunc eleifend magna ornare enim.
                  Non malesuada amet pulvinar mus. Diam massa ac eget mauris. Mi
                  ut enim in egestas massa. Bibendum nec rutrum sed commodo.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* Our Coaches */}
      <section className="section_top">
        <div className="container">
          <h2 className="title text-blue rocket text-center">Our Coaching</h2>
          <div className="inner-margin">
            <Coach />
          </div>
        </div>
      </section>
      {/* Our Coaches */}
      {/* Coaching Philosophy */}
      <section className="section_top">
        <div className="container">
          <div className="grid_2_to_1 gap5">
            <div>
              <h2 className="title text-blue rocket">Coaching Philosophy</h2>
              <p className="paragraph text-gray justify-center mt-2">
                Lorem ipsum dolor sit amet consectetur. Et ante imperdiet
                porttitor vulputate id. Ultrices id lectus lectus consequat
                porttitor lobortis. Morbi sit nunc eleifend magna ornare enim.
                Non malesuada amet pulvinar mus. Diam massa ac eget mauris. Mi
                ut enim in egestas massa. Bibendum nec rutrum sed commodo.
              </p>
            </div>
            <div>
              <Image
                src={players}
                alt="cricket player"
                className="img-fluid block margin-auto"
              />
            </div>
          </div>
        </div>
      </section>
      {/* coach team */}
      <section className="section_top">
        <div className="container">
          <h2 className="title text-blue rocket text-center">
            Coaching Specialization
          </h2>
          <p className="paragraph text-gray text-center mt-2">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
            optio nobis fugit tempore magni quia, sequi molestias unde numquam
            velit beatae laboriosam cum ipsa a, voluptate enim harum. Quisquam,
            minima.
          </p>
          <p className="paragraph text-gray text-center mt-2">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
            optio nobis fugit tempore magni quia, sequi molestias unde numquam
            velit beatae laboriosam cum ipsa a, voluptate enim harum. Quisquam,
            minima.
          </p>
          <p className="paragraph text-gray text-center mt-2">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium
            optio nobis fugit tempore magni quia, sequi molestias unde numquam
            velit beatae laboriosam cum ipsa a, voluptate enim harum. Quisquam,
            minima.
          </p>
        </div>
      </section>
      {/* testimonial */}
      <section className="section_top testpos">
        <div className="container">
          <div className="sectionpadingfull bg3">
            <div className="desktopview">
              <Image
                src={messageblue}
                alt="cricket player"
                className="messageiconblue"
              />
            </div>
            <h2 className="title text-blue rocket text-center">Testimonials</h2>
            <div className="inner-margin">
              <CoachTestimonial />
            </div>
            <div className="desktopview">
              <Image
                src={message}
                alt="cricket player"
                className="messageiconnew"
              />
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default pages;
