// images
import banner from "@/assets/banner/contactbanner.png";
import bannermob from "@/assets/banner/contactbannermob.png";
import Banner from "@/components/banner/Banner";
import GridGallery from "./gallery/Gallery";
export const metadata = {
  title: "Gallery",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
      <Banner
        banner={banner}
        mobilebanner={bannermob}
        text="Get in Touch with Our Cricket Experts"
      />
      <section className="section_top">
        <div className="container">
          <GridGallery />
        </div>
      </section>
    </>
  );
};

export default page;
